<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IS54" failures="0" tests="4" name="HollandCRM_Prod_Smoke.ContactContactlistUnderSales" time="2.084" errors="4" timestamp="21 Jan 2019 16:32:29 GMT">
  <testcase classname="HollandCRM_Prod_Smoke.ContactContactlistUnderSales" name="FirstName_LastName_Displayed_ContactContactListGeneralInformation" time="0.000">
    <error message="Method ContactContactlistUnderSales.FirstName_LastName_Displayed_ContactContactListGeneralInformation()[pri:3, instance:HollandCRM_Prod_Smoke.ContactContactlistUnderSales@38467116] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method ContactContactlistUnderSales.FirstName_LastName_Displayed_ContactContactListGeneralInformation()[pri:3, instance:HollandCRM_Prod_Smoke.ContactContactlistUnderSales@38467116] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- FirstName_LastName_Displayed_ContactContactListGeneralInformation -->
  <testcase classname="HollandCRM_Prod_Smoke.ContactContactlistUnderSales" name="GeneralInformation_Displayed_ContactListUnderSales" time="0.000">
    <error message="Method ContactContactlistUnderSales.GeneralInformation_Displayed_ContactListUnderSales(java.util.Hashtable)[pri:2, instance:HollandCRM_Prod_Smoke.ContactContactlistUnderSales@38467116] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method ContactContactlistUnderSales.GeneralInformation_Displayed_ContactListUnderSales(java.util.Hashtable)[pri:2, instance:HollandCRM_Prod_Smoke.ContactContactlistUnderSales@38467116] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- GeneralInformation_Displayed_ContactListUnderSales -->
  <testcase classname="HollandCRM_Prod_Smoke.ContactContactlistUnderSales" name="ContactContactlistUnderSales" time="0.000">
    <error message="Method ContactContactlistUnderSales.ContactContactlistUnderSales()[pri:4, instance:HollandCRM_Prod_Smoke.ContactContactlistUnderSales@38467116] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method ContactContactlistUnderSales.ContactContactlistUnderSales()[pri:4, instance:HollandCRM_Prod_Smoke.ContactContactlistUnderSales@38467116] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- ContactContactlistUnderSales -->
  <testcase classname="HollandCRM_Prod_Smoke.ContactContactlistUnderSales" name="AccessToContactListUnderSales" time="2.084">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.datadriven.frame.base.BaseTest.openBrowser(BaseTest.java:156)
	at HollandCRM_Prod_Smoke.ContactContactlistUnderSales.AccessToContactListUnderSales(ContactContactlistUnderSales.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- AccessToContactListUnderSales -->
</testsuite> <!-- HollandCRM_Prod_Smoke.ContactContactlistUnderSales -->
