<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IS54" failures="0" tests="3" name="HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales" time="3.316" errors="3" timestamp="21 Jan 2019 16:32:29 GMT">
  <testcase classname="HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales" name="Access_Resource_Resourcelist_Sales" time="0.000">
    <error message="Method Access_Resource_Resourcelist_Sales.Access_Resource_Resourcelist_Sales()[pri:3, instance:HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales@1040be71] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method Access_Resource_Resourcelist_Sales.Access_Resource_Resourcelist_Sales()[pri:3, instance:HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales@1040be71] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- Access_Resource_Resourcelist_Sales -->
  <testcase classname="HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales" name="ValidateAccessToResourceUnderSales" time="3.316">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.datadriven.frame.base.BaseTest.openBrowser(BaseTest.java:156)
	at HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales.ValidateAccessToResourceUnderSales(Access_Resource_Resourcelist_Sales.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- ValidateAccessToResourceUnderSales -->
  <testcase classname="HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales" name="Validate_NavToSelectedResource_Name_Displayed" time="0.000">
    <error message="Method Access_Resource_Resourcelist_Sales.Validate_NavToSelectedResource_Name_Displayed(java.util.Hashtable)[pri:2, instance:HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales@1040be71] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method Access_Resource_Resourcelist_Sales.Validate_NavToSelectedResource_Name_Displayed(java.util.Hashtable)[pri:2, instance:HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales@1040be71] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:844)
]]>
    </error>
  </testcase> <!-- Validate_NavToSelectedResource_Name_Displayed -->
</testsuite> <!-- HollandCRM_Prod_Smoke.Access_Resource_Resourcelist_Sales -->
